artifacts_root: artifacts

mlflow_config:
  dagshub_username: Teungtran
  dagshub_repo_name: Mlops_Prac
  tracking_uri: https://dagshub.com/Teungtran/Mlops_Prac.mlflow
  experiment_name: MLOps_Pipeline_Stages

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/train.csv
  test_size: 0.2
  random_state: 42

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
  tokenizer_path: artifacts/prepare_base_model/tokenizer.pkl

model_params:
  maxlen: 200
  num_words: 5000
  embedding_dim: 128
  batch_size: 64
  epochs: 5
  filters: 128
  kernel_size: 5
  dropout_rate: 0.2

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  train_data_path: artifacts/training/train_data.csv
  test_data_path: artifacts/training/test_data.csv
  tokenizer_path: artifacts/prepare_base_model/tokenizer.pkl
  bucket_name: mlop


evaluation:
  root_dir: artifacts/evaluation
  trained_model_path: artifacts/training/model.h5
  metrics_file: artifacts/evaluation/metrics.json
  plots_dir: artifacts/evaluation/plots