artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_version_dir: artifacts/data_version
  local_data_file: artifacts/data_ingestion/input_raw.csv
  test_size: 0.2
  random_state: 42
  bucket_name: churn_data_version

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  model_version_dir: artifacts/model_version
  data_version_dir: artifacts/data_version
  criterion: entropy
  max_depth: 30 
  max_features: log2
  min_samples_leaf: 2
  n_estimators: 500
  random_state: 42

training:
  root_dir: artifacts/training
  model_version_dir: artifacts/model_version
  data_version_dir: artifacts/data_version
  bucket_name: churn_data_version

evaluation:
  root_dir: artifacts/evaluation
  model_version_dir: artifacts/model_version
  data_version_dir: artifacts/data_version
  plots_dir: artifacts/evaluation/plots